### ISSUE TITLE
a project with binary V8 snapshot packaging

### ISSUE THREAD

**Issue by lgodard** [Gisto/nwjs-shell-builder#14]
Hi all,

Just a few words to let you know that I've published a new project based on *nwjs-shell-builder* :  https://github.com/lgodard/nwjs-node-packager

https://github.com/lgodard/nwjs-node-packager allows to package (linux, win, osx) a nwjs app with optionally binary V8 snapshot to protect/obfuscate sources, and is well maintained :grinning: 

Feel free to post any remark and contribution to the project!

Many thanks to nwjs-shell-builder for the inspiration!

Laurent

**Comment by sanusart** [comment]
Great thanks for the notice @lgodard ! Updated the deprecation notice in the readme to suggest this as an alternative.
