### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmanchhabra** [Gisto/nwjs-shell-builder#15]
Hi @sanusart!

I'm a member of [NW Utils](https://github.com/nwutils/). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones.

Hope to chat soon!

Best Regards
Ayush

**Comment by sanusart** [comment]
Hey @A9U3HC this one is pretty old and unmaintained. Are you sure?

**Comment by ayushmanchhabra** [comment]
@sanusart Yup - this may sound crazy but people are using all sorts of outdated tools for their builds! By moving the project under the NW Utils org, it allows the project at receive fixes/feats and at the very least be in maintainance mode.

**Comment by sanusart** [comment]
Sure thing then, 
@morsdyce any objections?

**Comment by morsdyce** [comment]
> Sure thing then, 
> @morsdyce any objections?

Nope, feel free to move it

**Comment by sanusart** [comment]
@A9U3HC I think I need to be a member
![Uploading Screenshot_2023-05-26-14-21-55-364_com.android.chrome-edit.jpg…]()

**Comment by ayushmanchhabra** [comment]
@sanusart Invite sent! Once you accept and repo is tranferred, I'll add you as an admin so nothing really changes from your end.

**Comment by ayushmanchhabra** [comment]
@morsdyce @sanusart thanks!

**Comment by sanusart** [comment]
@A9U3HC thank you!
