### ISSUE TITLE
Would you be interested in an OSX .pkg building extension that works on linux?

### ISSUE THREAD

**Issue by SchizoDuckie** [Gisto/nwjs-shell-builder#8]
I just created this:

And would be more than happy to create a pull request to inject it into nwjs-shell-builder

``` shell
#!/bin/bash

BUILD_DIR="/var/www/deploy/TMP/osx-ia32/latest-git"
BASE_DIR="/var/www/deploy/osx" 
VERSION="1.1.3"
IDENTIFIER="tv.duckie"
APPNAME="DuckieTV"
BACKGROUND="/var/www/DuckieTV/img/duckietv.png"

rm -rf "$BASE_DIR/darwin"
mkdir -p "$BASE_DIR/darwin/flat/Resources/en.lproj"
mkdir -p "$BASE_DIR/darwin/flat/base.pkg/"
mkdir -p "$BASE_DIR/darwin/root/Applications"
cp -R $BUILD_DIR/*.* $BASE_DIR/darwin/root/Applications
cp $BACKGROUND $BASE_DIR/darwin/flat/Resources/en.lproj/background
NUM_FILES=$(find ${BASE_DIR}/darwin/root | wc -l)
INSTALL_KB_SIZE=$(du -k -s ${BASE_DIR}/darwin/root | awk '{print $1}')

cat <<EOF > ${BASE_DIR}/darwin/flat/base.pkg/PackageInfo
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<pkg-info overwrite-permissions="true" relocatable="false" identifier="${IDENTIFIER}" postinstall-action="none" version="${VERSION}" format-version="2" generator-version="InstallCmds-502 (14B25)" auth="root">
    <payload numberOfFiles="${NUM_FILES}" installKBytes="${INSTALL_KB_SIZE}"/>
    <bundle-version>
        <bundle id="${IDENTIFIER}" CFBundleIdentifier="${IDENTIFIER}" path="./Applications/DuckieTV.app" CFBundleVersion="1.3.0"/>
    </bundle-version>
    <update-bundle/>
    <atomic-update-bundle/>
    <strict-identifier/>
    <relocate/>
    <scripts/>
</pkg-info>
EOF

cat <<EOF > ${BASE_DIR}/darwin/flat/Distribution
<?xml version="1.0" encoding="utf-8"?>
<installer-script minSpecVersion="1.000000" authoringTool="com.apple.PackageMaker" authoringToolVersion="3.0.3" authoringToolBuild="174">
    <title>${APPNAME} ${VERSION}</title>
    <options customize="never" allow-external-scripts="no"/>
    <background file="background" alignment="bottomleft" scaling="none"/>
    <domains enable_anywhere="true"/>
    <installation-check script="pm_install_check();"/>
    <script>function pm_install_check() {
      if(!(system.compareVersions(system.version.ProductVersion,'10.5') >= 0)) {
        my.result.title = 'Failure';
        my.result.message = 'You need at least Mac OS X 10.5 to install ${APPNAME}.';
        my.result.type = 'Fatal';
        return false;
      }
      return true;
    }
    </script>
    <choices-outline>
        <line choice="choice1"/>
    </choices-outline>
    <choice id="choice1" title="base">
        <pkg-ref id="${IDENTIFIER}.base.pkg"/>
    </choice>
    <pkg-ref id="${IDENTIFIER}.base.pkg" installKBytes="${INSTALL_KB_SIZE}" version="${VERSION}" auth="Root">#base.pkg</pkg-ref>
</installer-script>
EOF

PKG_LOCATION="/var/www/deploy/osx/${APPNAME}-${VERSION}.pkg"

( cd ${BASE_DIR}/darwin/root && find . | cpio -o --format odc --owner 0:80 | gzip -c ) > ${BASE_DIR}/darwin/flat/base.pkg/Payload
mkbom -u 0 -g 80 ${BASE_DIR}/darwin/root ${BASE_DIR}/darwin/flat/base.pkg/Bom 
( cd ${BASE_DIR}/darwin/flat/ && xar --compression none -cf "${PKG_LOCATION}" * ) 
echo "osx package has been built: ${PKG_LOCATION}"
```

which will deliver you a nice .pkg that looks like this: 
![image](https://cloud.githubusercontent.com/assets/111710/8551396/98ec2208-24d6-11e5-8c3c-2d4816b79a30.png)

I'm also planning to create a win32 installer using innosetup, which we should also be able to run directly from linux using wine.

**Comment by morsdyce** [comment]
That would be interesting, we tried previously creating DMG files on linux with no success.
Do you think pkg is appropriate as most applications that do not modify files outside their application scope do not use it.

How does it affect file size?

We actually already have a script that creates a windows installer, but Its not part of this repo.

@sanusart Maybe it would be nice if we could add a flag to generate installers and work on installers for every platform What do you think?

P.S thanks for all the pull requests

**Comment by SchizoDuckie** [comment]
You're very welcome :)

Building dmg files on any other platform than osx is impossible indeed. I currently have a hacky script that offloads that to a VM by scp'ing it there, and feeding it to [this script](https://github.com/SchizoDuckie/DuckieTV/blob/angular/build-mac.sh)

but frankly this is a shitty solution, which is why I wrote the new script I posted here. Being able to package it on linux will make the whole world happy.

There isn't a single opensource project that can completely generate an osx and windows installer plus a linux tgz on linux (or cross-platform, for that matter), and I think we should make nwjs-shell-builder the first :)

They should be under a flag of course and be optional, which is why i'm kicking off this discussion.

The file size isn't super, about twice the size of the regular release, but we can zip that again ofcourse.
I'm not a mac pro myself, but it's the only alternative as far as I can tell. I found many others deploying pkg files (jenkins being one of them)

**Comment by sanusart** [comment]
It would be really cool if we could optionally create installers for all platforms (featured behind flag off course).

Building on VM requires Mac VM or am I missing something?

Currently we have separate [release script](https://github.com/Gisto/Gisto/blob/master/build/release.sh) which is not part of this repository (@morsdyce mentioned earlier) as it is tailored for our application (Gisto). It currently able to generate INNO setup installer for Windows and scripted installer for Linux, but as I've wrote, it is currently tailored for Gisto. The Mac DMGs @morsdyce builds on his Mac (after we failed to generate DMG by script from Linux).

The important thing about _nwjs-shell-builder_ is that it can be ran x-platform as of now. Wouldn want to sacrifice this.

Thanks for contributing @SchizoDuckie

**Comment by SchizoDuckie** [comment]
Technically we should be able to make it working cross-platform. The buidl-mac.sh example I gave above indeed offloads the work to a mac virtual machine (as I don't own a mac, and didn't want to 'call a friend' every time I make a release). The script I started this thread with successfully generates a .pkg on linux though! (The screenshot is proof that I can then actually install it on my mac vm) 

There is a win32 binary of mkbom ( http://hogliux.github.io/bomutils/index.html ) and there is an xar port for cygwin http://sourceforge.net/p/cygwin-ports/xar/ci/master/tree/

With that, we have all the tools we need I think \o/ and don't even have to make many changes to my new implementation, other than detecting if the required binaries are available and if not, provide instructions on how to get them.

**Comment by SchizoDuckie** [comment]
I clarified some of my previous comments to show that this is a proposition to show that we can build .pkg files on windows and linux

**Comment by sanusart** [comment]
So I guess we shall create a separate branch and start over there?

**Comment by SchizoDuckie** [comment]
I'm spending the weekend on fleshing out some more of my personal build scripts, where I've added nsis installers, and the mac .pkg builder as well. I'll see if I can work that into something that integrates with nwjs-shell-builder.sh 

I will send some pull requests when that's done, but if you already want to start on a branch I'm all for that as well

**Comment by sanusart** [comment]
So far adjusted for creating windows EXEs and Linux install scripts.
@SchizoDuckie any luck with OSX stuff?

**Comment by SchizoDuckie** [comment]
@sanusart I've been busy on my local project, but do have building OSX on linux working. Made some adjustments to the script because I needed a temp dir and stuff, so didn't merge yet.

Current example code here:

https://github.com/SchizoDuckie/DuckieTV/blob/angular/build/build_mac.sh
Example .pkg for those interested: https://github.com/SchizoDuckie/DuckieTV/releases/latest

**Comment by sanusart** [comment]
Thanks @SchizoDuckie, example looks great. I'll look into the the script and try to incorporate it in.

**Comment by SchizoDuckie** [comment]
@sanusart I also modified you NSIS builder a bit for windows and made it almost generic: 

https://github.com/SchizoDuckie/DuckieTV/blob/angular/build/build_windows.sh

**Comment by sanusart** [comment]
@SchizoDuckie Hmmm. I think is as much generic as it may be at this stage (in [development branch](https://github.com/Gisto/nwjs-shell-builder/blob/development/resources/windows/app.nsi) I mean), but improvement is much needed - that's for sure. 
Anyway we should probably get it all to the working state first, and then perform some cleanup and code review of some kind. 
I've added some basic 'hooks' system (via cdf5b99) in order to be able to cut in in the middle of the script run.

**Comment by SchizoDuckie** [comment]
Those hook scripts look like a great idea! :+1:

**Comment by sanusart** [comment]
@SchizoDuckie @morsdyce 
So what you think is the best, to stick with [config.json](https://github.com/Gisto/nwjs-shell-builder/blob/58f834183676ba2e0b4373b008d01ae1c7d7c40e/config.json) or go with CMD switches?

**Comment by morsdyce** [comment]
I'll always prefer config.json than a bunch of CMD switches (if i have to do more than 4).
Of course that the config json should be filled with all the default options and supply a flag to load one from a different location so you can point it to the one in your app in your CI server.

**Comment by sanusart** [comment]
> Of course that the config json should be filled with all the default options and supply a flag to load one from a different location so you can point it to the one in your app in your CI server.

OK, added via 3f87750

**Comment by morsdyce** [comment]
:+1:

**Comment by sanusart** [comment]
So it seems that `development` branch as of now able to pack Linux and Windows installers. OSX installer works but the app is not starting after installation for some reason :cry: 
Hopefully I'll get my hands on a Mac soon and sort it out.

**Comment by SchizoDuckie** [comment]
I just checked the code and it looks brilliant. Can't spot any potential errors or mistakes so far. I'll try to build the new DuckieTV release with it in the coming week and test it on my mac VM

**Comment by sanusart** [comment]
Cool. Let us know about any findings why it may not run.

**Comment by SchizoDuckie** [comment]
Absolutely top notch work! Awesome!

**Comment by sanusart** [comment]
:+1:
